### ISSUE TITLE
Every time I go by my audio file  of this error. TypeError: argument of type 'WindowsPath' is not iterable can you explain why?

### ISSUE THREAD

**Issue by viny33** [facebookresearch/demucs#2] opened 2019-11-27 20:16 UTC
(demucs) C:\Users\Vinicius111\Desktop\demucs-master\demucs-master>python -m demucs.separate --dl -n demucs C:\Users\Vinicius111\Desktop\demucs-master\demucs-master\test.mp3
  0%|                                                                                            | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\Vinicius111\Anaconda3\envs\demucs\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Vinicius111\Anaconda3\envs\demucs\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Vinicius111\Desktop\demucs-master\demucs-master\demucs\separate.py", line 132, in <module>
    main()
  File "C:\Users\Vinicius111\Desktop\demucs-master\demucs-master\demucs\separate.py", line 116, in main
    wav = AudioFile(track).read(streams=0, samplerate=44100, channels=2).to(args.device)
  File "C:\Users\Vinicius111\Desktop\demucs-master\demucs-master\demucs\audio.py", line 95, in read
    streams = np.array(range(len(self)))[streams]
  File "C:\Users\Vinicius111\Desktop\demucs-master\demucs-master\demucs\audio.py", line 58, in __len__
    return len(self._audio_streams)
  File "C:\Users\Vinicius111\Desktop\demucs-master\demucs-master\demucs\audio.py", line 53, in _audio_streams
    index for index, stream in enumerate(self.info["streams"])
  File "C:\Users\Vinicius111\Desktop\demucs-master\demucs-master\demucs\audio.py", line 43, in info
    self._info = _read_info(self.path)
  File "C:\Users\Vinicius111\Desktop\demucs-master\demucs-master\demucs\audio.py", line 19, in _read_info
    check=True)
  File "C:\Users\Vinicius111\Anaconda3\envs\demucs\lib\subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\Vinicius111\Anaconda3\envs\demucs\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Vinicius111\Anaconda3\envs\demucs\lib\subprocess.py", line 1148, in _execute_child
    args = list2cmdline(args)
  File "C:\Users\Vinicius111\Anaconda3\envs\demucs\lib\subprocess.py", line 555, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: argument of type 'WindowsPath' is not iterable

**Comment by adefossez** [comment] 2019-11-28 01:01
Why version of python are you using?

**Comment by adefossez** [comment] 2019-11-28 01:07
Can you try again after having updated the repository? I think I have made a fix, but I do not have Windows, so I cannot try myself.

**Comment by vitacon** [comment] 2019-11-28 10:47
I think I had the same problem yesterday... 
(Windows` 10 64, Anaconda3-2019.10-Windows-x86_64.exe):

```

(demucs) C:\programy\demucs-master>python -m demucs.separate --dl -n tasnet --shifts=0 --split sub.wav
100%|---------------------------------------------------------------------------------| 44.1M/44.1M [00:42<00:00, 1.03MB/s]
  0%|                                                                                                | 0/1 [00:00<?, ?it/s]

Traceback (most recent call last):
  File "C:\Users\Condak\.conda\envs\demucs\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Condak\.conda\envs\demucs\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\programy\demucs-master\demucs\separate.py", line 132, in <module>
    main()
  File "C:\programy\demucs-master\demucs\separate.py", line 116, in main
    wav = AudioFile(track).read(streams=0, samplerate=44100, channels=2).to(args.device)
  File "C:\programy\demucs-master\demucs\audio.py", line 95, in read
    streams = np.array(range(len(self)))[streams]
  File "C:\programy\demucs-master\demucs\audio.py", line 58, in __len__
    return len(self._audio_streams)
  File "C:\programy\demucs-master\demucs\audio.py", line 53, in _audio_streams
    index for index, stream in enumerate(self.info["streams"])
  File "C:\programy\demucs-master\demucs\audio.py", line 43, in info
    self._info = _read_info(self.path)
  File "C:\programy\demucs-master\demucs\audio.py", line 19, in _read_info
    check=True)
  File "C:\Users\Condak\.conda\envs\demucs\lib\subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\Condak\.conda\envs\demucs\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Condak\.conda\envs\demucs\lib\subprocess.py", line 1119, in _execute_child
    args = list2cmdline(args)
  File "C:\Users\Condak\.conda\envs\demucs\lib\subprocess.py", line 530, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: argument of type 'WindowsPath' is not iterable

```

With today's version, I get this:

```
(demucs) C:\programy\demucs-master>python -m demucs.separate --dl -n demucs sub.wav
  0%|                                                                                         | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\Condak\.conda\envs\demucs\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None, "__main__", mod_spec)
  File "C:\Users\Condak\.conda\envs\demucs\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\programy\demucs-master\demucs\separate.py", line 132, in <module>
    main()
  File "C:\programy\demucs-master\demucs\separate.py", line 116, in main
    wav = AudioFile(track).read(streams=0, samplerate=44100, channels=2).to(args.device)
  File "C:\programy\demucs-master\demucs\audio.py", line 130, in read
    sp.run(command, check=True)
  File "C:\Users\Condak\.conda\envs\demucs\lib\subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ffmpeg', '-y', '-loglevel', 'panic', '-i', 'sub.wav', '-map', '0:0', '-threads', '1', '-f', 'f32le', '-ar', '44100', 'C:\\Users\\Condak\\AppData\\Local\\Temp\\tmpbgudkge8']' returned non-zero exit status 1.

```
The folder 'C:\\Users\\Condak\\AppData\\Local\\Temp\\tmpbgudkge8' does not exists indeed.

I modified audio.py...
```
        command += ['-loglevel', 'debug']
        command += ['-report']

```
...and then I got
`C:\Users\Condak\AppData\Local\Temp\tmpzeykv5qg: Permission denied
`

Running Anaconda as admin did not change anything except the temporary folder name.

```
Opening an output file: C:\Users\Condak\AppData\Local\Temp\tmp6l00frty.
[file @ 000002cb7fc941c0] Setting default whitelist 'file,crypto'
C:\Users\Condak\AppData\Local\Temp\tmp6l00frty: Permission denied

```
Surprisingly, "md C:\Users\Condak\AppData\Local\Temp\tmp6l00frty" works fine.

**Comment by adefossez** [comment] 2019-11-28 14:31
@vitacon  thanks for the report. Turns out `NamedTemporaryFile` cannot be used in the same way on Unix-systems and Windows.
@vitacon or @viny33  I have made a tentative fix, can you update your repo and try again?
Thanks!

**Comment by vitacon** [comment] 2019-11-28 16:11
@adefossez It works for me now. Thanks! =)

Just one more minor detail: as far as I know there is no "python3" in Windows version of Anaconda (just "python.exe") so you might mention it in your instructions.

**Comment by TronRin** [comment] 2019-11-28 16:51
I had the same problems as above, but now i get this using the cpu one:
RuntimeError: CUDA out of memory. Tried to allocate 1.54 GiB (GPU 0; 6.00 GiB total capacity; 2.65 GiB already allocated; 159.62 MiB free; 1.61 GiB cached)
I assume it's something on my end, but why does it talk about CUDA if i'm not using the gpu one?
While installing the gpu one i get an error of some kind so i just tried using the cpu and after the other errors i get this now. I did a clean install of the env for demucs just in case and no dice.

**Comment by TronRin** [comment] 2019-11-28 17:25
Okay, an update. I managed to install the gpu one by changing cudatoolkit ver to 10.1 but it still gave the error, but i finally figured out i should have addec '-d cpu' to my commandline. But the problem with cuda is that it uses my intergrated gpu by intel instead of my main gpu which Geforce RTX 2060. Or so I believe is the cause of the error.

**Comment by adefossez** [comment] 2019-11-28 18:25
@TronRin Normally you can select which gpu is used with CUDA_VISIBLE_DEVICES. If you run `nvidia-smi` for instance does it see the two GPUs you have? 
Can you try updating your repository and trying again? I have changed the default flags for `separate` and now it should be more memory friendly, but maybe it is still too much to run on 6GB. Are you using Demucs or Tasnet?

**Comment by adefossez** [comment] 2019-12-06 14:29
Closing for now, please open a new issue if you still have a problem :)

**Closed by adefossez** 2019-12-06 14:29 UTC
