### ISSUE TITLE
combine all of the model's output, so the noise gets suppressed and the signals get boosted? 

### ISSUE THREAD

**Issue by JaeDukSeo** [facebookresearch/demucs#140] opened 2020-10-28 17:21 UTC
First of all, thank you for this research. SUPER DOPE!

Just a question, would there be a way to combine all of the model's output, so the noise gets suppressed and the signals get boosted?

**Comment by adefossez** [comment] 2020-10-29 10:09
Duplicate of 
https://github.com/facebookresearch/demucs/issues/139

**Closed by adefossez** 2020-10-29 10:09 UTC
